### ISSUE TITLE
Segfault in Jacobi CG solver

### ISSUE THREAD

**Issue by dbeurle** [viennacl/viennacl-dev#269]
I've come across an interesting segfault when compiling with optimisations inside a larger finite element program.  The offending function:

```cpp
using sparse_matrix = Eigen::SparseMatrix<double, Eigen::RowMajor>;
using vector = Eigen::VectorXd;

void conjugate_gradient_ocl::solve(sparse_matrix const& A, vector& x, vector const& b)
{
    using vcl_sparse_matrix = viennacl::compressed_matrix<double>;
    using vcl_vector = viennacl::vector<double>;

    std::cout << "Allocating data on compute device..." << std::endl;
    std::cout << "A.rows() = " << A.rows() << ", A.cols() = " << A.cols() << "\n";

    vcl_sparse_matrix vcl_A(A.rows(), A.cols());
    vcl_vector vcl_b(b.size());

    std::cout << "Allocated data on compute device" << std::endl;

    viennacl::copy(A, vcl_A);
    viennacl::copy(b, vcl_b);

    std::cout << "Copied data to compute device" << std::endl;

    viennacl::linalg::cg_tag solver_tag(residual_tolerance, max_iterations);

    viennacl::linalg::jacobi_precond<vcl_sparse_matrix> vcl_jacobi(vcl_A,
                                                                   viennacl::linalg::jacobi_tag());

    vcl_vector const vcl_x = viennacl::linalg::solve(vcl_A, vcl_b, solver_tag, vcl_jacobi);

    viennacl::copy(vcl_x, x);

    std::cout << std::string(6, ' ') << "Conjugate Gradient iterations: " << solver_tag.iters()
              << " (max. " << max_iterations << "), estimated error: " << solver_tag.error()
              << " (min. " << residual_tolerance << ")\n";
}
```
The backtrace:

```
Thread 1 "neonfe" received signal SIGSEGV, Segmentation fault.
clRetainMemObject (memobj=0x7800) at ocl_icd_loader_gen.c:225
225	  RETURN(((struct _cl_mem *)memobj)->dispatch->clRetainMemObject(memobj));
(gdb) bt
#0  clRetainMemObject (memobj=0x7800) at ocl_icd_loader_gen.c:225
#1  0x00000000005026c0 in neon::conjugate_gradient_ocl::solve(Eigen::SparseMatrix<double, 1, int> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&) ()
#2  0x00000000004323bc in neon::mechanics::static_matrix<neon::mechanics::solid::mesh<neon::mechanics::solid::submesh> >::perform_equilibrium_iterations() ()
```
A minimal working example doesn't seem to segfault with the same compiler options.  Here is a summary of what seems to cause the segfault:

- `-O2 -DNDEBUG -g` segfault
- `-O2 -DNDEBUG` segfault
- `-O3 -DNDEBUG` segfault
- `<no optimisation>` works

I observe the same behaviour with gcc and clang.

Are there any suggested steps to debug this further?

**Comment by karlrupp** [comment]
@dbeurle Sorry for the late response.

How did this issue turn out? Did you observe similar behavior on other platforms (hardware and software)?

**Comment by dbeurle** [comment]
Thanks for the reply!  Let me have another look at it.  Last I recall, it was likely a bug in the vendor implementation, but I'll post some info regarding OS / driver.
